# Generated by Django 6.0.3 on 2026-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha7_escola", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curso",
            old_name="profesor",
            new_name="professor",
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="ficha7_escola/fotos"
            ),
        ),
    ]
