# Generated by Django 6.0.3 on 2026-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/fotos"
                    ),
                ),
                ("link", models.URLField(blank=True)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
    ]
