# Generated by Django 6.0.3 on 2026-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("linkedin", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="link",
            field=models.CharField(max_length=255),
        ),
    ]
