# Generated by Django 6.0.3 on 2026-04-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_docente_alter_tecnologia_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadeira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        related_name="cadeiras", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadeiras",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="cadeiras", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
