# Generated by Django 6.0.3 on 2026-04-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaTematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                ("email_autor", models.EmailField(blank=True, max_length=254)),
                ("supervisor", models.CharField(max_length=255)),
                (
                    "grau",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("mestrado", "Mestrado"),
                            ("doutoramento", "Doutoramento"),
                        ],
                        default="mestrado",
                        max_length=50,
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("resumo", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("link", models.URLField(blank=True)),
                ("download", models.URLField(blank=True)),
                (
                    "destaque",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Normal"),
                            (1, "Interessante"),
                            (2, "Muito Interessante"),
                            (3, "Destaque"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.areatematica"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
